// <auto-generated />
namespace AuthApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addNamefieldtoUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNamefieldtoUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201902070750030_add Name field to User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
